### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by p5yk0** [foo123/Contemplate#1]
I think some docs are needed about API reference on php/js side.

**Comment by foo123** [comment]
Sure what do you have in mind?  Personaly i think the best documentation is 1. self-documented and clean code, 2. good and understandable examples, a 3. a concise and precise reference with provided features, functions/etc..

**Note** that the engine tries to keep the functions and methods exactly the same on all implementations of the engine (i.e js/php/python)

**Comment by foo123** [comment]
Have updated documentation (see manual.md)
In case sth else is needed, open another issue.
Closing this
