### ISSUE TITLE
Pipe Template Functions / Plugins

### ISSUE THREAD

**Issue by kouts** [foo123/Contemplate#3]
Hi, great work on Contamplate, can't wait to use it on my next project. Is there any way you can implement a "pipe" feature to template functions i.e to chain two or more functions?

**Comment by foo123** [comment]
Hi, thanks. Emm, i'm not sure what you mean "pipe"?

**Comment by kouts** [comment]
I found it, ok, for example: <% %lcfirst(%uppercase($user_name)) %>
I'm trying to grasp all features of contemplate, I'm sure that if there was some more examples/documentation contemplate would be one of the most famous js template engines today.

**Comment by foo123** [comment]
Ok,  well if you have an idea for documentation examples feel free to suggest or even create a pull request. Of course there is a page with the API reference (manual.md) and an online interactive page where one can test the engine live
